import type { Activity, Lead, Workspace, WorkspaceMember } from "@/types";

export const MOCK_USER = {
  id: "user-1",
  name: "Otávio Augusto",
  email: "otavio@pipeflow.com.br",
  avatarInitials: "OA",
};

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: "ws-1",
    name: "Agência Digital",
    slug: "agencia-digital",
    plan: "pro",
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "ws-2",
    name: "Consultoria B2B",
    slug: "consultoria-b2b",
    plan: "free",
    created_at: "2024-03-20T14:30:00Z",
  },
  {
    id: "ws-3",
    name: "E-commerce Moda",
    slug: "ecommerce-moda",
    plan: "free",
    created_at: "2024-06-01T09:00:00Z",
  },
];

export const MOCK_CURRENT_WORKSPACE = MOCK_WORKSPACES[0];

export const MOCK_MEMBERS: WorkspaceMember[] = [
  {
    id: "member-1",
    workspace_id: "ws-1",
    user_id: "user-1",
    role: "admin",
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "member-2",
    workspace_id: "ws-1",
    user_id: "user-2",
    role: "member",
    created_at: "2024-02-01T10:00:00Z",
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    workspace_id: "ws-1",
    name: "Rafael Mendes",
    email: "rafael.mendes@techbrasil.com.br",
    phone: "(11) 99123-4567",
    company: "TechBrasil Soluções",
    role: "Diretor de TI",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "lead-2",
    workspace_id: "ws-1",
    name: "Juliana Costa",
    email: "juliana.costa@grupoinova.com.br",
    phone: "(21) 98765-4321",
    company: "Grupo Inova",
    role: "CEO",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-01-15T14:00:00Z",
    updated_at: "2024-01-16T09:00:00Z",
  },
  {
    id: "lead-3",
    workspace_id: "ws-1",
    name: "Bruno Carvalho",
    email: "b.carvalho@marketingpro.com.br",
    phone: "(31) 97654-3210",
    company: "Marketing Pro",
    role: "Gerente de Marketing",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-01-20T11:30:00Z",
    updated_at: "2024-01-20T11:30:00Z",
  },
  {
    id: "lead-4",
    workspace_id: "ws-1",
    name: "Fernanda Lima",
    email: "fernanda@consultoriafl.com.br",
    phone: "(11) 96543-2109",
    company: "Consultoria FL",
    role: "Sócia-Diretora",
    status: "inativo",
    owner_id: "user-1",
    created_at: "2024-01-25T09:00:00Z",
    updated_at: "2024-02-01T10:00:00Z",
  },
  {
    id: "lead-5",
    workspace_id: "ws-1",
    name: "Marcelo Rocha",
    email: "marcelo.rocha@softlabs.com.br",
    phone: "(41) 95432-1098",
    company: "SoftLabs",
    role: "CTO",
    status: "perdido",
    owner_id: "user-1",
    created_at: "2024-02-01T10:00:00Z",
    updated_at: "2024-02-15T16:00:00Z",
  },
  {
    id: "lead-6",
    workspace_id: "ws-1",
    name: "Camila Ferreira",
    email: "camilaf@ecommercemais.com.br",
    phone: "(21) 94321-0987",
    company: "E-commerce Mais",
    role: "Gerente de Vendas",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-02-05T13:00:00Z",
    updated_at: "2024-02-05T13:00:00Z",
  },
  {
    id: "lead-7",
    workspace_id: "ws-1",
    name: "Diego Santos",
    email: "diego@agenciadigits.com.br",
    phone: "(51) 93210-9876",
    company: "Agência Digits",
    role: "Fundador",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-02-10T08:00:00Z",
    updated_at: "2024-02-10T08:00:00Z",
  },
  {
    id: "lead-8",
    workspace_id: "ws-1",
    name: "Amanda Oliveira",
    email: "amanda.oliveira@financasme.com.br",
    phone: "(61) 92109-8765",
    company: "Finanças ME",
    role: "CFO",
    status: "inativo",
    owner_id: "user-1",
    created_at: "2024-02-14T15:30:00Z",
    updated_at: "2024-02-20T10:00:00Z",
  },
  {
    id: "lead-9",
    workspace_id: "ws-1",
    name: "Thiago Almeida",
    email: "thiago@construtoramt.com.br",
    phone: "(71) 91098-7654",
    company: "Construtora MT",
    role: "Engenheiro Chefe",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-02-18T10:00:00Z",
    updated_at: "2024-02-18T10:00:00Z",
  },
  {
    id: "lead-10",
    workspace_id: "ws-1",
    name: "Isabela Gomes",
    email: "isa.gomes@clinicasaude.com.br",
    phone: "(85) 90987-6543",
    company: "Clínica Saúde Total",
    role: "Diretora Administrativa",
    status: "perdido",
    owner_id: "user-1",
    created_at: "2024-02-22T11:00:00Z",
    updated_at: "2024-03-01T09:00:00Z",
  },
  {
    id: "lead-11",
    workspace_id: "ws-1",
    name: "Leonardo Pinto",
    email: "leo.pinto@startuplab.com.br",
    phone: "(11) 89876-5432",
    company: "StartupLab",
    role: "Co-fundador",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-02-25T14:00:00Z",
    updated_at: "2024-02-25T14:00:00Z",
  },
  {
    id: "lead-12",
    workspace_id: "ws-1",
    name: "Natalia Braga",
    email: "natalia@rhmais.com.br",
    phone: "(48) 88765-4321",
    company: "RH Mais",
    role: "Head de Pessoas",
    status: "inativo",
    owner_id: "user-1",
    created_at: "2024-03-01T09:30:00Z",
    updated_at: "2024-03-05T11:00:00Z",
  },
  {
    id: "lead-13",
    workspace_id: "ws-1",
    name: "Rodrigo Tavares",
    email: "rodrigo@logisticart.com.br",
    phone: "(19) 87654-3210",
    company: "LogísticArt",
    role: "Diretor Comercial",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-03-08T08:30:00Z",
    updated_at: "2024-03-08T08:30:00Z",
  },
  {
    id: "lead-14",
    workspace_id: "ws-1",
    name: "Priscila Nunes",
    email: "pri.nunes@educamais.com.br",
    phone: "(62) 86543-2109",
    company: "Educa Mais",
    role: "Coordenadora Pedagógica",
    status: "perdido",
    owner_id: "user-1",
    created_at: "2024-03-12T10:00:00Z",
    updated_at: "2024-03-20T14:00:00Z",
  },
  {
    id: "lead-15",
    workspace_id: "ws-1",
    name: "Felipe Azevedo",
    email: "felipe@imoveisaz.com.br",
    phone: "(11) 85432-1098",
    company: "Imóveis AZ",
    role: "Corretor Sênior",
    status: "ativo",
    owner_id: "user-1",
    created_at: "2024-03-15T11:30:00Z",
    updated_at: "2024-03-15T11:30:00Z",
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "call",
    description:
      "Apresentação inicial do produto. Cliente demonstrou forte interesse em automação de processos internos.",
    author_id: "user-1",
    created_at: "2024-01-12T10:30:00Z",
  },
  {
    id: "act-2",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "email",
    description:
      "Envio de proposta comercial com preços, condições de pagamento e escopo detalhado do contrato.",
    author_id: "user-1",
    created_at: "2024-01-15T14:00:00Z",
  },
  {
    id: "act-3",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "meeting",
    description:
      "Reunião de alinhamento com equipe técnica do cliente para levantamento de requisitos e cronograma.",
    author_id: "user-1",
    created_at: "2024-01-18T09:00:00Z",
  },
  {
    id: "act-4",
    workspace_id: "ws-1",
    lead_id: "lead-1",
    type: "note",
    description:
      "Cliente solicitou prazo de 15 dias para análise interna. Aguardando retorno do comitê de tecnologia.",
    author_id: "user-1",
    created_at: "2024-01-20T16:00:00Z",
  },
  {
    id: "act-5",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "call",
    description:
      "Primeiro contato via telefone. Juliana quer expandir as operações digitais da empresa em 2024.",
    author_id: "user-1",
    created_at: "2024-01-16T11:00:00Z",
  },
  {
    id: "act-6",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "meeting",
    description:
      "Demo da plataforma realizada remotamente via Google Meet. Feedback muito positivo da equipe.",
    author_id: "user-1",
    created_at: "2024-01-19T15:30:00Z",
  },
  {
    id: "act-7",
    workspace_id: "ws-1",
    lead_id: "lead-2",
    type: "email",
    description:
      "Encaminhamento de cases de sucesso e comparativo com concorrentes, conforme solicitado na reunião.",
    author_id: "user-1",
    created_at: "2024-01-22T10:00:00Z",
  },
  {
    id: "act-8",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    type: "email",
    description:
      "Respondeu solicitação de orçamento personalizado. Aguardando aprovação da diretoria executiva.",
    author_id: "user-1",
    created_at: "2024-01-21T10:00:00Z",
  },
  {
    id: "act-9",
    workspace_id: "ws-1",
    lead_id: "lead-3",
    type: "call",
    description:
      "Follow-up telefônico. Bruno confirmou interesse mas pediu ajuste no prazo de implementação.",
    author_id: "user-1",
    created_at: "2024-01-24T14:30:00Z",
  },
  {
    id: "act-10",
    workspace_id: "ws-1",
    lead_id: "lead-6",
    type: "meeting",
    description:
      "Apresentação presencial no escritório da empresa. Camila trouxe toda a equipe de vendas para participar.",
    author_id: "user-1",
    created_at: "2024-02-07T10:00:00Z",
  },
  {
    id: "act-11",
    workspace_id: "ws-1",
    lead_id: "lead-6",
    type: "note",
    description:
      "Empresa avalia também uma solução concorrente. Precisamos reforçar os diferenciais do produto.",
    author_id: "user-1",
    created_at: "2024-02-08T17:00:00Z",
  },
];
